src/components/App/Register/register.js
src/components/App/SignIn/signIn.js
src/components/UI/buttons/GradientBtn.js
src/services/Auth.js
src/services/LoginCheck.js
src/services/RegisterCheck.js
src/store/reducers/log.js
src/utils/Auth/index.js
src/utils/index.js

* Hardware:
* Toolchain:
* SDK:

Fix after move repo

---

src/components/App/Register/register.js
src/components/App/SignIn/signIn.js
src/containers/Home/Home.js
src/services/CaseList.js
src/services/JobList.js
src/services/SaveCard.js
src/store/actions/cardCheck.js
src/store/actions/index.js
src/store/actions/registerUser.js
src/store/reducers/home.js
src/store/reducers/user.js

Creer une liste de jobs avec le retour de l'endpoint Jobs
* Hardware:
* Toolchain:
* SDK:

add jobs users from api to subbcribe form

---

src/components/App/Register/register.js
src/components/App/SignIn/signIn.js

* Hardware:
* Toolchain:
* SDK:

Lory entrer button

---

src/containers/Profile/profile.js

Added logout button in profile.js without style
Resolve # (50)
> https://github.com/DentiioApp/dentiio-front/issues/50
Tested on the browser. No unit test performed yet
* Hardware:
* Toolchain:
* SDK:

add logout button

---

src/components/App/SignIn/SignIn.js
src/index.js

* Hardware:
* Toolchain:
* SDK:

Timeout notification 

---

yarn.lock

* Hardware:
* Toolchain:
* SDK:

fix yarn lock security dependancy bit

---

src/App.js
src/components/App/CaseItem/CaseItem.js
src/components/App/DetailCase/PatientDetail.js
src/components/App/Register/Register.js
src/components/UI/Icon/Profile/iconProfile.js
src/components/UI/Icon/iconNotifSubject/iconNotifSubject.js
src/config/index.js
src/containers/Home/Home.js
src/services/Users.js
src/store/actions/index.js
src/store/reducers/cases.js

* Hardware:
* Toolchain:
* SDK:

Lory fix register

---

.github/workflows/linter.yml
package.json
yarn.lock

Upgrade dependencies for security
* Hardware:
* Toolchain:
* SDK:

upgrade dependencies

---

src/components/App/CaseItem/CaseItem.js
src/components/App/CasesList/CasesList.js
src/components/App/Header/Header.js
src/components/UI/Icon/Header/add.js
src/components/UI/Icon/Header/notification.js
src/components/UI/buttons/favButton.js
src/containers/CasePost/CasePost.js
src/containers/Cases/Cases.js
src/containers/QuestionPost/QuestionPost.js
src/index.js

Add page for post clinical case and post question 
Add button in header
* Hardware:
* Toolchain:
* SDK:

Button add case feature

---

src/containers/Favorites/Favorites.js
src/containers/Profile/Profile.js

fix errors in the console
Resolve # (74)
* Hardware:
* Toolchain:
* SDK:

#74 fix errors

---

src/components/App/ClinicCase/ClinicCase.js
src/components/App/Diagnostic/Diagnostic.js
src/components/App/TreatPlan/TreatPlan.js
src/services/Cases.js

* Hardware:
* Toolchain:
* SDK:

Fix css old branch (don't link to issue)

---

src/components/App/Patient/Patient.js
src/services/Cases.js

* Hardware:
* Toolchain:
* SDK:

add var page to clical case , add label to age in create case

---

package.json
src/components/App/CaseItem/CaseItem.js
src/components/App/CasesList/CasesList.js
src/components/App/DetailCase/CardPlanTreatment.js
src/components/App/Header/Header.js
src/components/App/SignIn/SignIn.js
src/components/UI/Paginator/Paginator.js
src/components/UI/buttons/favButton.js
src/containers/CasePost/CasePost.js
src/services/Cases.js
src/store/actions/Cases.js
src/store/actions/index.js
src/store/reducers/cases.js
yarn.lock

* Hardware:
* Toolchain:
* SDK:

Ajouter des cas en favoris

---

src/containers/DetailCase/DetailCase.js

* Hardware:
* Toolchain:
* SDK:

resolve warning

---

src/index.js

* Hardware:
* Toolchain:
* SDK:

comment devtools

---

src/services/Auth.js
src/store/reducers/user.js

* Hardware:
* Toolchain:
* SDK:

add id to redux

---

src/components/App/Register/Register.js

require cgu in register
* Hardware:
* Toolchain:
* SDK:

require cgu in register

---

src/components/App/SignIn/SignIn.js
src/components/App/Status/Status.js
src/services/Users.js

* Hardware:
* Toolchain:
* SDK:

comment add cps process

---

src/components/App/Patient/Patient.js
src/components/UI/Dawers/Spinner.js
src/containers/Favorites/Favorites.js
src/services/Cases.js

* Hardware:
* Toolchain:
* SDK:

Page favorite

---

src/containers/DetailCase/DetailCase.js
src/containers/Favorites/Favorites.js
src/containers/Profile/Profile.js

* Hardware:
* Toolchain:
* SDK:

Lory factorise code

---

src/components/App/CaseItem/CaseItem.js
src/components/App/DetailCase/Rating.js
src/containers/DetailCase/DetailCase.js
src/containers/Profile/EditProfile.js
src/containers/UserAvatar/Tab.js

* Hardware:
* Toolchain:
* SDK:

Note case design 

---

package.json
src/components/App/Cases/CasesList/CasesList.js
yarn.lock

* Hardware:
* Toolchain:
* SDK:

Upgrade node-sasse

---

src/components/App/Cases/CasesList/CasesList.js
src/components/App/Cases/PostCase/Patient/Patient.js
src/components/UI/ColorTheme/ColorTheme.js
src/components/UI/Loading/LoadingCasesList.js
src/components/UI/Search/CasesSearch/CasesSearch.js
src/containers/CGU/CGU.js
src/containers/Cases/Cases.js
src/containers/DetailCase/DetailCase.js
src/containers/Favorites/Favorites.js
src/containers/Profile/EditProfile.js
src/containers/Profile/Profile.js
src/containers/QuestionPost/QuestionPost.js
src/containers/UserAvatar/UserAvatar.js

loading in home && begin of dark mode
* Hardware:
* Toolchain:
* SDK:

Upgrade loading

---

package.json
src/components/App/Cases/CaseItem/CaseItem.js
src/components/App/Cases/PostCase/Diagnostic/Diagnostic.js
src/components/App/Cases/PostCase/Exam/Exam.js
src/components/App/Cases/PostCase/Finalisation/Finalisation.js
src/components/App/Cases/PostCase/New/New.js
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
src/components/App/Cases/PostCase/Patient/Patient.js
src/components/UI/Dawers/CategoriesCases.js
src/components/UI/Steppers/PostCaseStepper.js
src/containers/CasePost/CasePost.js
src/index.js
src/services/Cases.js
src/services/Patient.js
src/store/actions/CasesAction.js
src/store/actions/index.js
src/store/reducers/casesReducer.js
yarn.lock

* Hardware:
* Toolchain:
* SDK:

SEND MULTIPLE REQUEST WITH FILES TO API 

---

Makefile

update the makefile

---

.github/workflows/preprod.yaml

add the deploy pre prodution config 
Resolve #158

 Deploy preprod front

---

src/components/App/Cases/Comments/Comments.js
src/containers/DetailCase/DetailCase.js
src/services/Comment.js
src/store/actions/index.js

User can add comments to the clinical case, 
User's informations (name, avatar, comment, date) are displayed
Resolve # (113)
Browser
* Hardware:
* Toolchain:
* SDK:

Mounia comments box

---

src/components/App/Cases/CaseItem/CaseItem.js
src/components/App/Cases/CaseItem/caseItem.scss
src/components/App/Cases/CasesList/CasesList.js
src/components/App/Cases/DetailCase/PatientDetail.js
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
src/components/UI/Loading/LoadingCasesList.js
src/components/UI/RightMenuIcon/rightMenuIcon.js

* Hardware:
* Toolchain:
* SDK:

Detail roro

---

src/containers/UserAvatar/Tab.js

* Hardware:
* Toolchain:
* SDK:

beard bug ok

---

src/components/App/Cases/CaseItem/CaseItem.js
src/components/App/Cases/DetailCase/NavbarDetail.js
src/components/UI/titleHeader/titleHeaderMobile.js

fix scroll navbar on mobile section
put redirection to /case on mobile navbar
* Hardware:
* Toolchain:
* SDK:

on mobile section redirect logo to case && navbar scroll ok

---

src/components/App/Cases/Comments/Comments.js
src/components/App/Cases/Comments/comments.scss
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
src/services/Cases.js
src/store/actions/CasesAction.js

Hide avatar on mobile screen
* Hardware:
* Toolchain:
* SDK:

Hide avatar on mobile screen

---

src/components/App/Cases/Comments/Comments.js

on comments section change hour and minutes to 2 digit and fix click on sendIcon
* Hardware:
* Toolchain:
* SDK:

change hour and minutes to 2 digit && sendIcon click

---

404.html

add a page for the wrong url, 404 page
Resolve #161

feature 404 page 

---

src/components/App/Auth/Header/AuthHeader.js
src/components/App/Auth/SignIn/SignIn.js
src/components/App/Auth/SignIn/signIn.scss
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
src/containers/Cases/Cases.js
src/services/Users.js

* Hardware:
* Toolchain:
* SDK:

Log connexion done

---

src/components/App/Auth/SignIn/SignIn.js
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js

* Hardware:
* Toolchain:
* SDK:

delete toast connexion & add case

---

src/components/App/Cases/CaseItem/caseItem.scss
src/components/App/Cases/CasesList/CasesList.js

* Hardware:
* Toolchain:
* SDK:

design caseitem

---

src/components/App/Auth/SignIn/SignIn.js
src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js

* Hardware:
* Toolchain:
* SDK:

CAse item disign

---

src/components/App/Cases/DetailCase/NavbarDetail.js
src/components/App/Cases/DetailCase/PatientDetail.js
src/containers/DetailCase/DetailCase.js

* Hardware:
* Toolchain:
* SDK:

Bug detail case
